# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dumbo', '0004_auto_20160602_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
