# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dumbo', '0005_auto_20160602_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Whats the issue?')),
                ('attachment', models.FileField(blank=True, upload_to='attachment/')),
                ('tag', models.CharField(choices=[('UNCONFIRMED', 'UNCONFIRMED'), ('CONFIRMED', 'CONFIRMED'), ('PATCH', 'PATCH'), ('CLOSED', 'CLOSED')], default='UNCONFIRMED', max_length=10, verbose_name='Add some tags to the issue')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dumbo.Project')),
            ],
        ),
    ]
