# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumbo', '0010_auto_20160604_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Is this a private project?'),
        ),
    ]
